version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - $PWD/data:/var/lib/grafana
    depends_on:
      - prometheus

  script:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    ports:
      - 8000:8000
    command: python src/main.py
